FROM python:3

WORKDIR /.

# Copy source code
COPY . .

# Install system dependencies
RUN apt-get update && apt-get install -y libgl1-mesa-glx libglib2.0-0

# Create virtual environment and install dependencies
RUN python -m venv venv
RUN /bin/bash -c "source venv/bin/activate && pip install --no-cache-dir -r requirements.txt"

# Expose port and start server
EXPOSE 9999
CMD ["/bin/bash", "-c", "source venv/bin/activate && uvicorn main:app --host=0.0.0.0 --port=9999"]